### ISSUE TITLE
Error fetching advisories: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by iljah** [fmidev/pecasus-dashboard#2]
Did a yarn build and yarn start on my laptop and otherwise everything seemed to fail correctly due to lack of credentials but I got this when selecting advisory archive tab:
```
Error fetching advisories: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
I'm running
```
$ nodejs-yarn --version
1.13.0
```
and checkout from few h ago.

**Comment by aarokorhonen** [comment]
This is symptomatic of an unhandled error in backend APIs. I wrapped all backend API endpoints and frontend fetches with sane default handlers, leading to more robust app behavior and  more accurate error messages.
