### ISSUE TITLE
Necessary date arithmetic?

### ISSUE THREAD

**Issue by iljah** [fmidev/pecasus-dashboard#3]
Is there an existing function to convert between dates and days of year? I'm guessing e.g. https://github.com/fmidev/pecasus-dashboard/blob/85be23b937b09892ccab0c9b1c497082afb51726/backend/api/repository-overview.js#L12 will fail with leap seconds. What about leap days? Handling leap seconds probably isn't important but surviving leap days (like Feb 29 in less than 2 months) seems important.

**Comment by aarokorhonen** [comment]
Good point. I replaced this logic with Moment.js' `dayOfYear`, which reduces application code surface area.
